/* =====================================================================
   002_lyiweb_seed_home.sql — เนื้อหาปัจจุบันของหน้าแรก → lyiweb_items
   GENERATED by tools/build-seed-home.php from includes/home-data.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • รันซ้ำได้: แต่ละ list ใส่เฉพาะเมื่อยังไม่มีแถวของ list นั้นเลย (ไม่ทับเนื้อหาที่แก้ในหลังบ้านแล้ว)
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* home.partners — หน้าแรก · แถบคำเลื่อนใต้ภาพหลัก (8 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.partners')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 10, NULL, NULL, N'{"name":"SPORTSWEAR","tag":"PERFORMANCE"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 20, NULL, NULL, N'{"name":"ACTIVEWEAR","tag":"STRETCH"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 30, NULL, NULL, N'{"name":"COMPRESSION","tag":"SUPPORT"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 40, NULL, NULL, N'{"name":"TEAMWEAR","tag":"DURABILITY"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 50, NULL, NULL, N'{"name":"UNDERWEAR","tag":"COMFORT"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 60, NULL, NULL, N'{"name":"FOOTWEAR","tag":"GRIP"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 70, NULL, NULL, N'{"name":"OUTDOOR","tag":"WEBBING"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.partners', 80, NULL, NULL, N'{"name":"LIFESTYLE","tag":"FASHION"}');
END

/* home.tiles — หน้าแรก · การ์ดจุดใช้งานบนเสื้อผ้า (8 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.tiles')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 10, N'{"title":"เทปคอหลัง"}', NULL, N'{"label":"BACK NECK TAPE","icon":"neck","img":"assets/img/applications/app-back-neck.jpg","dx":-240,"dy":120,"rot":-4,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 20, N'{"title":"ขอบเอว"}', NULL, N'{"label":"WAISTBAND","icon":"band","img":"assets/img/applications/app-waistband.jpg","dx":-80,"dy":140,"rot":2,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 30, N'{"title":"เทปตกแต่ง / แถบข้าง"}', NULL, N'{"label":"DECORATIVE TAPE","icon":"stripe","img":"assets/img/applications/app-decorative.jpg","dx":80,"dy":140,"rot":-2,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 40, N'{"title":"เชือกรูด"}', NULL, N'{"label":"DRAWCORD","icon":"cord","img":"assets/img/applications/app-drawcord.jpg","dx":240,"dy":120,"rot":4,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 50, N'{"title":"เทปกุ๊นคอและวงแขน"}', NULL, N'{"label":"NECKLINE & ARMHOLE","icon":"collar","img":"assets/img/applications/app-neckline.jpg","dx":-240,"dy":200,"rot":3,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 60, N'{"title":"ยางยืดใต้อก / สปอร์ตบรา"}', NULL, N'{"label":"UNDERBUST / BRA","icon":"collar","img":"assets/img/applications/app-underbust.jpg","dx":-80,"dy":220,"rot":-2,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 70, N'{"title":"ขอบชายเสื้อและปลายแขน"}', NULL, N'{"label":"JACKET HEM / CUFF","icon":"band","img":"assets/img/applications/app-jacket-hem.jpg","dx":80,"dy":220,"rot":2,"more":false}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.tiles', 80, N'{"title":"ผ้าคาดหัว ริสแบนด์ และอุปกรณ์กีฬา"}', NULL, N'{"label":"SPORTS ACCESSORIES","icon":"cap","img":"","dx":240,"dy":200,"rot":-3,"more":true}');
END

/* home.steps — หน้าแรก · ขั้นตอนการผลิต (6 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.steps')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.steps', 10, N'{"title":"เส้นด้าย & วัตถุดิบคุณภาพ","short":"เส้นด้าย","desc":"คัดเลือกเส้นด้าย ทั้งโพลีเอสเตอร์ ไนลอน และสแปนเดกซ์ ให้เหมาะกับโครงสร้าง ความยืดหยุ่น และสัมผัสที่ต้องการของแต่ละชิ้นงาน"}', NULL, N'{"n":"01","tag":"OEKO-TEX® STANDARD","img":"assets/img/process/bgvideo1.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.steps', 20, N'{"title":"ทอ / ถัก / ถักเชือก","short":"ทอ/ถัก/ถักเชือก","desc":"เครื่องจักรรองรับโครงสร้างงานทอ งานถัก และงานถักเชือกหลากหลายรูปแบบ ตั้งแต่งานละเอียด เนื้อนุ่ม ไปจนถึงงานที่ต้องการรับแรงสูง"}', NULL, N'{"n":"02","tag":"WEAVING · KNITTING · BRAIDING","img":"assets/img/process/nl.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.steps', 30, N'{"title":"โรงย้อมและห้องแล็บภายใน","short":"ย้อมสีและแล็บ","desc":"ระบบจ่ายสีย้อมอัตโนมัติ ควบคุมสูตรด้วยคอมพิวเตอร์ เทียบสีตามผ้าตัวอย่างและรหัส Pantone พร้อมจัดทำ Lab dip เพื่ออนุมัติสี ควบคุมคุณภาพสีตามมาตรฐานที่กำหนดในทุกล็อตการสั่งซื้อ"}', NULL, N'{"n":"03","tag":"PANTONE MATCHING","img":""}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.steps', 40, N'{"title":"Finishing — งานตกแต่งสำเร็จ","short":"Finishing","desc":"งานสกรีน พิมพ์ Sublimation ทำปลายเชือก (Tipping) ด้วยซิลิโคน โลหะ และฟิล์ม เคลือบซิลิโคนกันลื่น ตัดตามความยาว และปั๊มนูน–จม ทั้งตัวอักษรและโลโก้ พร้อมนำไปเย็บประกอบบนชิ้นงาน"}', NULL, N'{"n":"04","tag":"VERSATILE FINISHING","img":"assets/img/process/BRAIDING.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.steps', 50, N'{"title":"QC ตรวจสอบคุณภาพทุกล็อต","short":"QC ทุกล็อต","desc":"ตรวจสอบคุณภาพและทดสอบคุณสมบัติด้วยห้องแล็บภายใน ทั้งแรงดึง ความยืดหยุ่นหลังซัก และความคงทนของสี (Colorfastness) เพื่อให้ชิ้นงานผ่านเกณฑ์มาตรฐานที่กำหนดก่อนส่งมอบ"}', NULL, N'{"n":"05","tag":"IN-HOUSE LAB & QC","img":"assets/img/process/FINISHING.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.steps', 60, N'{"title":"ส่งมอบตรงเวลา ซัพพลายเออร์เดียว","short":"ส่งมอบตรงเวลา","desc":"ซัพพลายเออร์รายเดียวรับผิดชอบคุณภาพตลอดสาย ลด lead time และตัดปัญหาความผิดพลาดในการประสานงานระหว่างโรงงานย่อย"}', NULL, N'{"n":"06","tag":"RELIABLE DELIVERY","img":"assets/img/process/CROCHET.jpg"}');
END

/* home.swatches — หน้าแรก · ปุ่มสี Pantone (5 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.swatches')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.swatches', 10, NULL, NULL, N'{"name":"Flame Orange (CI)","hex":"#ff5a1f","glow":"rgba(255,90,31,0.4)","code":"PANTONE 16-1454 TCX","text":"#fff"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.swatches', 20, NULL, NULL, N'{"name":"Cyber Sport Blue","hex":"#1d63ff","glow":"rgba(29,99,255,0.4)","code":"PANTONE 19-4052 TCX","text":"#fff"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.swatches', 30, NULL, NULL, N'{"name":"Neon Acid Lime","hex":"#bfff00","glow":"rgba(191,255,0,0.4)","code":"PANTONE 13-0630 TCX","text":"#000"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.swatches', 40, NULL, NULL, N'{"name":"Stealth Obsidian","hex":"#1c1b20","glow":"rgba(28,27,32,0.4)","code":"PANTONE 19-3911 TCX","text":"#fff"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.swatches', 50, NULL, NULL, N'{"name":"Crimson Racing Red","hex":"#e61e38","glow":"rgba(230,30,56,0.4)","code":"PANTONE 18-1662 TCX","text":"#fff"}');
END

/* home.products — หน้าแรก · การ์ดหมวดสินค้า (6 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.products')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.products', 10, N'{"title":"ยางยืด / สายยืด (Elastic Webbing)","desc":"ยืดหยุ่นสม่ำเสมอ คืนรูปยอดเยี่ยม ไม่ย้วยหลังผ่านการซักนับร้อยครั้ง สำหรับขอบเอว สายบ่า และงาน activewear"}', NULL, N'{"label":"ELASTIC WEBBING","spec":"10mm – 120mm · Custom Elasticity","code":"PROD-01","img":"assets/img/products/prod-elastic.jpg?v=2"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.products', 20, N'{"title":"เทปทอ (Woven Tape)","desc":"โครงสร้างแน่น ทนทานต่อแรงดึงสูง คงรูปได้ดีเยี่ยม สำหรับสายรัดกระเป๋า แถบตกแต่ง และชิ้นส่วนโครงสร้าง"}', NULL, N'{"label":"WOVEN TAPE","spec":"High-Tensile Poly/Nylon","code":"PROD-02","img":"assets/img/products/prod-woven.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.products', 30, N'{"title":"เทปถัก Raschel / Crochet","desc":"น้ำหนักเบา ผิวสัมผัสนุ่มเป็นพิเศษ ระบายอากาศได้ดี เหมาะสำหรับ overlay และชิ้นงานสัมผัสผิวหนังโดยตรง"}', NULL, N'{"label":"RASCHEL & CROCHET","spec":"Soft-Touch · Breathable Mesh","code":"PROD-03","img":"assets/img/products/prod-knit.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.products', 40, N'{"title":"เชือก เชือกยางยืด (Cords & Elastic Cords)","desc":"เชือกกลม เชือกแบน เชือกยางยืด ถักเปีย พร้อมงาน tipping หัวเชือกครบทุกเทคนิค (ซิลิโคนจุ่ม, โลหะสลักโลโก้, ฟิล์มหด)"}', NULL, N'{"label":"CORDS & ELASTIC CORDS","spec":"Silicone / Metal / Shrink Tube","code":"PROD-04","img":"assets/img/products/prod-cord.jpg"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.products', 50, N'{"title":"ขอบเอว (Engineered Waistbands)","desc":"จุดที่ผู้สวมใส่รู้สึกในทุกวินาที ควบคุมทั้งความนุ่มนวลต่อผิวและแรงกระชับที่พอดีตัวสำหรับกางเกงกีฬา"}', NULL, N'{"label":"WAISTBANDS","spec":"Jacquard / Brushed Soft Finish","code":"PROD-05","img":"assets/img/products/prod-waistband.jpg?v=2"}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.products', 60, N'{"title":"งาน Finish หลากหลายแบบ (Finishing & Branding)","desc":"ต่อยอดเทปให้ครบทั้งฟังก์ชันและแบรนด์ — ซิลิโคนกันลื่น พิมพ์ลาย heat transfer ปั๊มนูน เลเซอร์ ตัดร้อน/ตัดเย็น ไปจนถึงงานป้ายเลเบล เลือกผสมได้ตามการใช้งาน"}', NULL, N'{"label":"FINISHING","spec":"Silicone / Print / Emboss / Laser / Labels","code":"PROD-06","img":"assets/img/products/prod-finishing.jpg"}');
END

/* home.gallery — หน้าแรก · ตัวอย่างสินค้า (รหัส LY…) (6 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.gallery')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.gallery', 10, NULL, NULL, N'{"code":"LY2086","type":"Elastic Jacquard","img":""}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.gallery', 20, NULL, NULL, N'{"code":"RLY1319","type":"Raschel Knit Tape","img":""}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.gallery', 30, NULL, NULL, N'{"code":"RLY1452","type":"Braided Cord Tipped","img":""}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.gallery', 40, NULL, NULL, N'{"code":"LY2101","type":"Silicone Grip Tape","img":""}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.gallery', 50, NULL, NULL, N'{"code":"RLY1377","type":"Engineered Waistband","img":""}');
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.gallery', 60, NULL, NULL, N'{"code":"LY2144","type":"Woven High-Tensile","img":""}');
END

/* home.faq — หน้าแรก · คำถามที่พบบ่อย (4 rows) */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = N'home.faq')
BEGIN
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.faq', 10, N'{"q":"สั่งผลิตขั้นต่ำ (MOQ) อยู่ที่เท่าไหร่?","a":"เรารองรับการสั่งผลิตจำนวนน้อยได้ ขั้นต่ำขึ้นอยู่กับประเภทชิ้นงาน โครงสร้าง และสี — ทั้งงานทดลองตลาด คอลเลกชันขนาดเล็ก ไปจนถึงออเดอร์ปริมาณมาก ส่วนงานพัฒนาใหม่ (R&D) เราจัดทำชิ้นงานตัวอย่าง (Sample Run) เพื่อทดสอบฟังก์ชันและสีก่อนผลิตจริงได้ ส่งแบบหรือโจทย์การใช้งานมาให้ทีมฝ่ายขายประเมินได้เลย"}', NULL, NULL);
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.faq', 20, N'{"q":"เทียบสีตามรหัส Pantone หรือตัวอย่างจริงได้ไหม?","a":"ได้แน่นอนครับ โรงงานมีโรงย้อมมาตรฐานในตัวและห้องแล็บเทียบสีอัตโนมัติ รองรับทั้งระบบ Pantone Matching System (TCX), การทำ Lab-dip และการเทียบสีตามชิ้นงานจริงของลูกค้า พร้อมการันตีค่าความต่างของสี (Delta-E) ให้อยู่ในเกณฑ์มาตรฐานที่แบรนด์กีฬาระดับโลกยอมรับ"}', NULL, NULL);
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.faq', 30, N'{"q":"ระยะเวลาในการพัฒนาตัวอย่างและผลิตจริงใช้เวลากี่วัน?","a":"การทำชิ้นงานตัวอย่าง (Sample Development) ใช้เวลาประมาณ 7 – 14 วันทำการหลังยืนยันแบบและเฉดสี สำหรับการผลิตล็อตจริงใช้เวลาประมาณ 20 – 30 วันทำการ ขึ้นอยู่กับปริมาณและความซับซ้อนของเทคนิคการตกแต่ง (Finishing)"}', NULL, NULL);
    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (N'home.faq', 40, N'{"q":"รับบริการพัฒนาสินค้าตามแบบเฉพาะ (OEM / ODM) หรือไม่?","a":"รับครับ ทีมงาน R&D ของเรามีประสบการณ์กว่า 40 ปีในการร่วมงานกับดีไซเนอร์และผู้จัดการฝ่ายจัดซื้อของแบรนด์กีฬาระดับโลก ตั้งแต่การให้คำปรึกษาเรื่องโครงสร้างเส้นด้าย การเลือกใช้วัสดุรีไซเคิล (Recycled Yarn) การปรับแรงดึง ไปจนถึงการขึ้นตัวอย่างเพื่อทดสอบการเย็บจริง"}', NULL, NULL);
END

COMMIT TRANSACTION;

/* ตรวจผล */
SELECT list_key, COUNT(*) AS rows_count FROM dbo.lyiweb_items GROUP BY list_key ORDER BY list_key;
