/* =====================================================================
   003_lyiweb_seed_site.sql — ข้อมูลติดต่อ (lyiweb_settings) + ชื่อหน้า/คำอธิบาย SEO (lyiweb_pages)
   GENERATED by tools/build-seed-site.php from includes/site-defaults.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • รันซ้ำได้: settings ใส่เฉพาะ key ที่ยังไม่มี · pages เติมเฉพาะช่องที่ยังว่าง (NULL) — ไม่ทับค่าที่แก้ในหลังบ้านแล้ว
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* settings */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'phone')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'phone', N'02-517-0768');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'phone_ext')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'phone_ext', N'120, 121');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'fax')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'fax', N'02-517-4888');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'email')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'email', N'sales@lyindustries.com');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'line_id')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'line_id', N'@lyindustries');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'line_url')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'line_url', N'https://line.me/R/ti/p/@lyindustries');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'company_th')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'company_th', N'บริษัท แอล วาย อินดัสตรีย์ จำกัด');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'address1_th')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'address1_th', N'124 ซอยรามอินทรา 109 ถนนพระยาสุเรนทร์ แขวงบางชัน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'address2_th')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'address2_th', N'เขตคลองสามวา กรุงเทพฯ 10510');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'company_en')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'company_en', N'L.Y. Industries Co., Ltd.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'address1_en')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'address1_en', N'124 Soi Ram Inthra 109, Phraya Suren Road, Bang Chan');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'address2_en')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'address2_en', N'Khlong Sam Wa, Bangkok 10510');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'hours_weekday_open')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'hours_weekday_open', N'08:30');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'hours_weekday_close')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'hours_weekday_close', N'17:30');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'hours_sat_open')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'hours_sat_open', N'08:30');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'hours_sat_close')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'hours_sat_close', N'12:00');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'trimrite_url')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'trimrite_url', N'https://www.trimrite.com/');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'inspiration_url')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'inspiration_url', N'https://www.lyindustries.com/lyinspirationhub/');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'og_image')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'og_image', N'assets/img/brand/og-image.jpg');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'org_alt_names')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'org_alt_names', N'LY Industries, L.Y. Industries, LYI');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'org_founding')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'org_founding', N'1978');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'addr_locality')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'addr_locality', N'Khlong Sam Wa');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'addr_region')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'addr_region', N'Bangkok');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'addr_postal')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'addr_postal', N'10510');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'addr_country')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'addr_country', N'TH');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'geo_lat')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'geo_lat', N'');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'geo_lng')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'geo_lng', N'');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'social_facebook')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'social_facebook', N'');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'social_instagram')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'social_instagram', N'');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'social_linkedin')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'social_linkedin', N'');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'social_youtube')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'social_youtube', N'');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = N'social_tiktok')
    INSERT dbo.lyiweb_settings (setting_key, value) VALUES (N'social_tiktok', N'');

/* pages (rows were created by 001_lyiweb_schema.sql) */
UPDATE dbo.lyiweb_pages SET title_th = N'L.Y. Industries (Hybrid) — Narrow Fabrics & Trims ครบวงจร มาตรฐานระดับโลก', updated_at = GETDATE() WHERE slug = N'home' AND title_th IS NULL;
UPDATE dbo.lyiweb_pages SET title_th = N'เกี่ยวกับ L.Y. Industries — ผู้ผลิต Narrow Fabrics & Trims ตั้งแต่ปี 1978', updated_at = GETDATE() WHERE slug = N'about' AND title_th IS NULL;
UPDATE dbo.lyiweb_pages SET meta_desc_th = N'L.Y. Industries Co., Ltd. ผู้ผลิต Narrow Fabrics และ Trims ครบวงจรในกรุงเทพฯ ตั้งแต่ปี 1978 — ยางยืด เทปทอ เทปถัก เชือก ขอบเอว และงาน finishing สำหรับแบรนด์กีฬาและแฟชั่นระดับโลก', updated_at = GETDATE() WHERE slug = N'about' AND meta_desc_th IS NULL;
UPDATE dbo.lyiweb_pages SET title_th = N'แคตตาล็อกสินค้า Narrow Fabric & Trims — ยางยืด เทปทอ เทปถัก เชือก | L.Y. Industries', updated_at = GETDATE() WHERE slug = N'catalog' AND title_th IS NULL;
UPDATE dbo.lyiweb_pages SET meta_desc_th = N'แคตตาล็อกสินค้า L.Y. Industries ผู้ผลิต Narrow Fabric & Trims ครบวงจรในกรุงเทพฯ — ยางยืด เทปทอ เทปถัก Raschel/Crochet เชือกรูด เชือกยางยืด ขอบเอว และงานพิมพ์โลโก้ สำหรับเสื้อผ้ากีฬา ชุดชั้นใน และแฟชั่น พร้อมรับพัฒนาตามสเปก', updated_at = GETDATE() WHERE slug = N'catalog' AND meta_desc_th IS NULL;
UPDATE dbo.lyiweb_pages SET title_th = N'ติดต่อ L.Y. Industries — ผู้ผลิต Narrow Fabric & Trims กรุงเทพฯ', updated_at = GETDATE() WHERE slug = N'contact' AND title_th IS NULL;
UPDATE dbo.lyiweb_pages SET meta_desc_th = N'ติดต่อ L.Y. Industries ผู้ผลิต Narrow Fabric และ Trims ครบวงจร (ยางยืด เทปทอ เทปถัก เชือกรูด ขอบเอว) ที่ 124 ซอยรามอินทรา 109 ถนนพระยาสุเรนทร์ แขวงบางชัน เขตคลองสามวา กรุงเทพฯ 10510 โทร 02-517-0768 ต่อ 120, 121 อีเมล sales@lyindustries.com LINE @lyindustries', updated_at = GETDATE() WHERE slug = N'contact' AND meta_desc_th IS NULL;

COMMIT TRANSACTION;

/* ตรวจผล */
SELECT setting_key, value FROM dbo.lyiweb_settings ORDER BY setting_key;
SELECT slug, title_th, LEN(meta_desc_th) AS meta_desc_len FROM dbo.lyiweb_pages ORDER BY id;
