/* =====================================================================
   004_lyiweb_seed_blocks.sql — ข้อความของแต่ละหน้า → lyiweb_blocks
   GENERATED by tools/build-seed-blocks.php from includes/blocks/<page>.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • รันซ้ำได้: ใส่เฉพาะ block ที่ยังไม่มี (page_slug + block_key) — ไม่ทับข้อความที่แก้ในหลังบ้านแล้ว
   • เพิ่มหน้าใหม่ภายหลัง: generate ไฟล์นี้ใหม่แล้วรันซ้ำได้เลย
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* about.php — 52 blocks */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'hero.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'hero.01', N'text', N'ABOUT L.Y. INDUSTRIES · SINCE 1978');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'hero.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'hero.02', N'text', N'โรงงาน Narrow Fabrics & Trims');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'hero.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'hero.03', N'text', N'ที่แบรนด์กีฬาระดับโลก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'hero.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'hero.04', N'text', N'ไว้วางใจ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'hero.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'hero.05', N'text', N'L.Y. Industries Co., Ltd. ผู้ผลิต Narrow Fabrics และ Trims ครบวงจรในกรุงเทพฯ ตั้งแต่ปี 1978 — ยางยืด เทปทอ เทปถัก เชือก ขอบเอว และงาน finishing ทุกขั้นตอนอยู่ใต้หลังคาเดียวกัน ตั้งแต่เส้นด้ายจนถึงชิ้นงานพร้อมเย็บ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.01', N'text', N'INSIDE THE FACTORY · BANGKOK');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.02', N'text', N'WEAVING · KNITTING · BRAIDING · DYEING · FINISHING');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.03', N'text', N'1978');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.04', N'text', N'ก่อตั้งในกรุงเทพฯ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.05', N'text', N'45+');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.06', N'text', N'ปีในอุตสาหกรรม Narrow Fabrics');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.07', N'text', N'OEKO-TEX®');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.08', N'text', N'Standard 100 · ผ่านข้อกำหนด RSL ของแบรนด์ระดับโลก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.09', N'text', N'Color Lab');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'video.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'video.10', N'text', N'โรงย้อมในตัว + แล็บเทียบสี Pantone');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.01', N'text', N'01 — OUR STORY');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.02', N'text', N'LYI สู่ผู้ผลิต Narrow Fabric & Trims ครบวงจร');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.03', N'text', N'L.Y. Industries เริ่มต้นในปี 1978');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.04', N'text', N'ในฐานะโรงทอผ้าแถบในกรุงเทพฯ ด้วยความเชื่อเดียวกับที่เรายึดถือมาจนวันนี้ —');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.05', N'text', N'Small parts bring great impact.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.06', N'text', N'ตลอดกว่า 40 ปี L.Y. Industries เชี่ยวชาญการผลิต Narrow Fabric ทั้งงาน Weaving, Knitting และ Braiding แบบครบวงจร ตั้งแต่ย้อมเส้นด้ายในโรงย้อมของเราเอง จนถึงงาน finishing ภายในโรงงานเดียวที่กรุงเทพฯ เราผลิตยางยืด เทปทอ เทปถัก เชือกรูด และขอบเอว สำหรับเสื้อผ้ากีฬา ชุดชั้นใน และแฟชั่น ภายใต้มาตรฐาน OEKO-TEX® Standard 100 — ได้สีและคุณภาพสม่ำเสมอทุกล็อต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.07', N'text', N'COMPANY');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.08', N'text', N'L.Y. Industries Co., Ltd.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.09', N'text', N'FOUNDED');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.10', N'text', N'1978 · กรุงเทพมหานคร');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.11', N'text', N'FACTORY');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.12', N'text', N'PRODUCTS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.13', N'text', N'ยางยืด · เทปทอ · เทปถัก Raschel/Crochet · เชือก เชือกยางยืด · ขอบเอว · งาน finishing');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.14', N'text', N'MARKETS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.15', N'text', N'แบรนด์เสื้อผ้ากีฬา ชุดชั้นใน และแฟชั่น ทั้งในประเทศและส่งออก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'story.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'story.16', N'text', N'CONTACT');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.01', N'text', N'02 — FACILITIES');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.02', N'text', N'ทุกกระบวนการ อยู่ในโรงงานเดียว');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.03', N'text', N'ตั้งแต่เส้นด้ายเข้าโรงงานจนถึงชิ้นงานพร้อมเย็บ เราควบคุมคุณภาพได้ทุกขั้นตอนด้วยตัวเอง');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.04', N'text', N'R&D');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.05', N'text', N'ทีมพัฒนาสินค้า');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.06', N'text', N'DYEING');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.07', N'text', N'ย้อมเส้นด้าย / ชิ้นงาน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.08', N'text', N'QUALITY LAB');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.09', N'text', N'Lab คุณภาพ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.10', N'text', N'CONSTRUCTION');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.11', N'text', N'งานโครงสร้าง ทอ ถัก เชือก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.12', N'text', N'FINISHING');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.13', N'text', N'งาน Finish หลากหลายแบบ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.14', N'text', N'QC');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'facilities.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'facilities.15', N'text', N'QC ทุกล็อตการผลิต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'cta.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'cta.01', N'text', N'START A PROJECT');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'cta.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'cta.02', N'text', N'มีแบบ ตัวอย่าง หรือแค่โจทย์การใช้งาน — ส่งมาคุยกันได้เลย');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'cta.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'cta.03', N'text', N'ทีม R&D และฝ่ายขายพร้อมประเมินวัสดุ สี และตัวอย่างให้ตามการใช้งานจริงของคุณ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'cta.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'cta.04', N'text', N'ขอใบเสนอราคา →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'cta.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'cta.05', N'text', N'© 2026 L.Y. INDUSTRIES CO., LTD.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'about' AND block_key = N'cta.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'about', N'cta.06', N'text', N'BANGKOK, THAILAND · EST. 1978');

/* catalog.php — 49 blocks */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'hero.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'hero.01', N'text', N'PRODUCT CATALOG');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'hero.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'hero.02', N'text', N'แคตตาล็อกสินค้า');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'hero.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'hero.03', N'text', N'Narrow Fabric & Trims ครบทุกประเภท ผลิตในโรงงานเดียวที่กรุงเทพฯ — ทุกรายการพัฒนาตามสเปกของแบรนด์ได้ ทั้งขนาด สี ความยืด และงาน finishing');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.01', N'text', N'01 — PRODUCT CATEGORIES');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.02', N'text', N'หมวดสินค้าหลัก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.03', N'text', N'PROD-01');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.04', N'text', N'ELASTIC WEBBING');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.05', N'text', N'ยางยืด / สายยืด (Elastic Webbing)');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.06', N'text', N'สินค้าเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.07', N'text', N'PROD-02');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.08', N'text', N'WOVEN TAPE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.09', N'text', N'เทปทอ (Woven Tape)');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.10', N'text', N'สินค้าเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.11', N'text', N'PROD-03');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.12', N'text', N'RASCHEL & CROCHET');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.13', N'text', N'เทปถัก Raschel / Crochet');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.14', N'text', N'สินค้าเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.15', N'text', N'PROD-04');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.16', N'text', N'CORDS & ELASTIC CORDS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.17', N'text', N'เชือก เชือกยางยืด (Cords & Elastic Cords)');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.18', N'text', N'สินค้าเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.19')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.19', N'text', N'PROD-05');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.20')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.20', N'text', N'WAISTBANDS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.21')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.21', N'text', N'ขอบเอว (Engineered Waistbands)');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.22')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.22', N'text', N'สินค้าเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.23')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.23', N'text', N'PROD-06');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.24')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.24', N'text', N'FINISHING');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.25')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.25', N'text', N'งาน Finish ต่างๆ และพิมพ์โลโก้ (Finishing & Branding)');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'categories.26')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'categories.26', N'text', N'สินค้าเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.01', N'text', N'02 — SAMPLE SPECIMENS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.02', N'text', N'ตัวอย่างสินค้าของเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.03', N'text', N'ทุกชิ้นมีรหัสอ้างอิงเฉพาะ ขอตัวอย่างจริงเพื่อเทียบสัมผัส หรือสั่งพัฒนาต่อยอดได้ทันที');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.04', N'text', N'LY2086');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.05', N'text', N'Elastic Jacquard');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.06', N'text', N'RLY1319');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.07', N'text', N'Raschel Knit Tape');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.08', N'text', N'RLY1452');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.09', N'text', N'Braided Cord Tipped');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.10', N'text', N'LY2101');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.11', N'text', N'Silicone Grip Tape');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.12', N'text', N'RLY1377');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.13', N'text', N'Engineered Waistband');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.14', N'text', N'LY2144');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.15', N'text', N'Woven High-Tensile');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.16', N'text', N'INSPIRATION HUB');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.17', N'text', N'ดูสินค้าทั้งหมดแบบ 3D');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.18', N'text', N'สำรวจแคตตาล็อกเต็มรูปแบบของเราบน Inspiration Hub หรือส่งสเปกมาให้ทีมช่วยเลือกวัสดุที่เหมาะกับงานของคุณ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.19')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.19', N'text', N'ดูแคตตาล็อกทั้งหมด ↗');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'catalog' AND block_key = N'samples.20')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'catalog', N'samples.20', N'text', N'ขอตัวอย่าง / ใบเสนอราคา →');

/* contact.php — 28 blocks */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'hero.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'hero.01', N'text', N'CONTACT L.Y. INDUSTRIES');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'hero.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'hero.02', N'text', N'ติดต่อเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.01', N'text', N'01 — SEND AN INQUIRY');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.02', N'text', N'ขอใบเสนอราคา / สอบถามข้อมูล');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.03', N'text', N'กรอกรายละเอียดคร่าว ๆ ทีมขายจะติดต่อกลับภายใน 24 ชั่วโมงทำการ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.04', N'text', N'ชื่อ-นามสกุล *');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.05', N'text', N'บริษัท / แบรนด์');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.06', N'text', N'อีเมล *');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.07', N'text', N'เบอร์โทร');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.08', N'text', N'สินค้าที่สนใจ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.09', N'text', N'ยางยืด / Elastic');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.10', N'text', N'เทปทอ / Woven Tape');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.11', N'text', N'เทปถัก Raschel / Crochet');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.12', N'text', N'เชือกรูด / Drawcord');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.13', N'text', N'ขอบเอว / Waistband');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.14', N'text', N'งานพิมพ์โลโก้ / Finishing');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.15', N'text', N'อื่น ๆ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.16', N'text', N'รายละเอียด (ขนาด สี จำนวน การใช้งาน) *');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.17', N'text', N'ส่งคำขอ →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.18', N'text', N'ADDRESS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.19')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.19', N'text', N'PHONE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.20')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.20', N'text', N'FAX');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.21')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.21', N'text', N'EMAIL');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.22')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.22', N'text', N'LINE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'form.23')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'form.23', N'text', N'HOURS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'map.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'map.01', N'text', N'02 — LOCATION');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'map.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'map.02', N'text', N'ที่อยู่ของเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'contact' AND block_key = N'map.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'contact', N'map.03', N'text', N'เปิดใน Google Maps ↗');

/* footer.php — 14 blocks */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.01', N'text', N'L.Y. INDUSTRIES CO., LTD.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.02', N'text', N'OPERATING HOURS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.03', N'text', N'SITEMAP');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.04', N'text', N'หน้าแรก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.05', N'text', N'แคตาล็อกสินค้า');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.06', N'text', N'TRIMRITE®');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.07', N'text', N'เกี่ยวกับเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.08', N'text', N'ติดต่อเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.09', N'text', N'คำถามพบบ่อย');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.10', N'text', N'QUALITY STANDARDS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.11', N'text', N'OEKO-TEX® Standard 100 Certified');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.12', N'text', N'สอดคล้องข้อกำหนด RSL ของแบรนด์กีฬาระดับโลก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.13', N'text', N'© 2026 L.Y. INDUSTRIES CO., LTD. ALL RIGHTS RESERVED.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'footer' AND block_key = N'main.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'footer', N'main.14', N'text', N'BANGKOK, THAILAND · EST. 1978');

/* home.php — 129 blocks */
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.01', N'text', N'ONE-STOP NARROW FABRICS & TRIMS · EST. 1978 · BANGKOK');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.02', N'text', N'Trims ที่ไม่เคยทำให้');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.03', N'text', N'ไลน์ผลิตของคุณ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.04', N'text', N'สะดุด');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.05', N'text', N'LY Industries');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.06', N'text', N'คือผู้ผลิต Narrow Fabric และ Trims ครบวงจรในกรุงเทพฯ ก่อตั้งปี 1978 ผลิตยางยืด เทปทอ เชือกรูด ขอบเอว และงานซิลิโคน ให้แบรนด์กีฬาระดับโลกมากว่า 40 ปี ด้วยการทอ ถัก ย้อม และตกแต่งสำเร็จในโรงงานเดียว — คุณภาพสม่ำเสมอทุกล็อต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.07', N'text', N'ขอใบเสนอราคา / Request a Quote');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.08', N'text', N'ขั้นตอนการผลิตของเรา ↓');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'hero.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'hero.09', N'text', N'SCROLL TO EXPLORE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.01', N'text', N'TRUSTED BY GLOBAL SPORTSWEAR & APPAREL LEADERS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.02', N'text', N'40+');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.03', N'text', N'ปีแห่งประสบการณ์');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.04', N'text', N'ผลิต narrow fabrics & trims ตั้งแต่ปี 1978');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.05', N'text', N'100%');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.06', N'text', N'One-Stop Solution');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.07', N'text', N'ทอ ถัก ย้อม Finishing จบในโรงงานเดียว');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.08', N'text', N'OEKO-TEX®');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.09', N'text', N'Standard 100 Certified');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.10', N'text', N'ปลอดภัย ไร้สารอันตราย ผ่านข้อกำหนด RSL');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.11', N'text', N'Custom Trims');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.12', N'text', N'พัฒนาตามแบบแบรนด์คุณ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'trust.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'trust.13', N'text', N'เลือกวัสดุ สี และรายละเอียดให้เหมาะกับงาน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'story.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'story.01', N'text', N'01 — THE ANATOMY OF A GARMENT');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'story.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'story.02', N'text', N'ทุกจุดบนเสื้อผ้ากีฬาที่ต้องใช้ Trims — เรามีให้ครบ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'story.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'story.03', N'text', N'คอหลัง · ขอบเอว · เทปตกแต่ง · เชือกรูด · กุ๊นคอและวงแขน · ใต้อก · ชายเสื้อและปลายแขน · อุปกรณ์กีฬา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'story.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'story.04', N'text', N'พร้อมพัฒนาตามแบบของคุณ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.01', N'text', N'02 — WHY IT MATTERS TO YOU');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.02', N'text', N'เพราะ Trims ชิ้นเล็ก ๆ ที่ไม่ได้คุณภาพ คือต้นทุนก้อนใหญ่ที่มองไม่เห็น');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.03', N'text', N'01');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.04', N'text', N'CONSISTENCY YOU CAN SEW ON');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.05', N'text', N'ไลน์ผลิตของคุณไม่สะดุด');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.06', N'text', N'มาตรฐานความยืดสม่ำเสมอทุกล็อต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.07', N'text', N'02');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.08', N'text', N'COLOR RIGHT, EVERY LOT');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.09', N'text', N'สีตรง ตรงทุกล็อต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.10', N'text', N'In-house Pantone Color Lab');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.11', N'text', N'03');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.12', N'text', N'ONE SUPPLIER, ZERO COORDINATION');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.13', N'text', N'จบทุกขั้นตอนในที่เดียว');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.14', N'text', N'ครบวงจรใต้หลังคาเดียวในกรุงเทพฯ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.15', N'text', N'04');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.16', N'text', N'FROM SKETCH TO SAMPLE, FAST');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.17', N'text', N'พัฒนาของใหม่ได้เร็ว');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'why.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'why.18', N'text', N'R&D ร่วมกับดีไซเนอร์แบรนด์');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'process.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'process.01', N'text', N'03 — PROCESS PIPELINE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'process.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'process.02', N'text', N'จากเส้นด้ายสู่ชิ้นงานสำเร็จ — ภายใต้การควบคุมทุกขั้นตอน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'specimens.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'specimens.01', N'text', N'04 — PRODUCT SPECIMENS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'specimens.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'specimens.02', N'text', N'Narrow Fabric & Trims ครบทุกประเภท');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'specimens.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'specimens.03', N'text', N'ออกแบบและพัฒนาเฉพาะสำหรับ activewear, sportswear, compression wear และ high-fashion');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'specimens.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'specimens.04', N'text', N'ขอรับแคตตาล็อก & ตัวอย่างสินค้า →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'specimens.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'specimens.05', N'text', N'สั่งผลิต →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.01', N'text', N'05 — R&D SERVICE · FROM SKETCH TO REALITY');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.02', N'text', N'เราพัฒนา Trims ให้เข้ากับการใช้งาน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.03', N'text', N'ทีม R&D ของเราทำงานร่วมกับดีไซเนอร์และ Product Developer ตั้งแต่สเก็ตช์แรก จนได้ตัวอย่างที่ใส่จริง ทดสอบจริง และพร้อมเข้าสู่การผลิตจริง');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.04', N'text', N'STRETCH %');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.05', N'text', N'RECOVERY');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.06', N'text', N'COMPRESSION');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.07', N'text', N'WIDTH & HAND-FEEL');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.08', N'text', N'GRIP');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.09', N'text', N'COLOR & BRANDING');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.10', N'text', N'IN-HOUSE R&D TEAM');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.11', N'text', N'ทีมพัฒนาคุยกับดีไซเนอร์ของคุณโดยตรง');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.12', N'text', N'01');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.13', N'text', N'SKETCH');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.14', N'text', N'รับโจทย์จากการใช้งาน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.15', N'text', N'ส่งมาได้ทั้งตัวอย่างจริง ไฟล์ภาพ สเก็ตช์ tech pack หรือแค่โจทย์การใช้งาน — เราแปลงเป็นสเปกทางเทคนิคให้');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.16', N'text', N'02');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.17', N'text', N'ENGINEER');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.18', N'text', N'ออกแบบโครงสร้างและวัสดุ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.19')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.19', N'text', N'ออกแบบโครงสร้างและเลือกวัสดุให้ตรงกับ requirements ของการใช้งาน อาทิ แรงดึง การคืนตัว และสัมผัสที่การใช้งานนั้นต้องการ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.20')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.20', N'text', N'03');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.21')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.21', N'text', N'SAMPLE & TEST');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.22')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.22', N'text', N'ตัวอย่างจริง ทดสอบจริง');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.23')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.23', N'text', N'ขึ้นตัวอย่างพร้อม Lab-dip สี ทดสอบแรงดึง การคืนตัว และความคงทน ปรับจนดีไซเนอร์ลองใส่แล้วพอใจ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.24')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.24', N'text', N'04');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.25')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.25', N'text', N'PRODUCTION');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.26')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.26', N'text', N'ขึ้นผลิตจริง พร้อมส่งมอบ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.27')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.27', N'text', N'ล็อกสเปกที่ผ่านการอนุมัติเป็นรหัสสินค้าของคุณ เข้าสู่การผลิตจริงตามกำหนด และส่งมอบในคุณภาพเดียวกันทุกล็อต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'rnd.28')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'rnd.28', N'text', N'เริ่มต้นพัฒนาชิ้นงานกับเรา →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.01', N'text', N'06 — IN-HOUSE DYEING & PANTONE LAB');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.02', N'text', N'โรงย้อมมาตรฐาน');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.03', N'text', N'สีตรงแม่นยำทุกล็อต');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.04', N'text', N'ระบบจ่ายสีย้อมอัตโนมัติและห้องแล็บเทียบสีมาตรฐานสากล');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.05', N'text', N'เทียบสีได้จาก Pantone TCX, Lab-dip หรือชิ้นงานตัวอย่างจริง');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.06', N'text', N'ควบคุมเฉดให้ตรงกันตั้งแต่ตัวอย่างแรกจนถึงการผลิตซ้ำ พร้อมรับประกันความคงทนของสีต่อการซัก เหงื่อ และแสง UV');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.07', N'text', N'ΔE<0.5');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.08', N'text', N'ค่าความต่างสีที่ยอมรับ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.09', N'text', N'TCX');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.10', N'text', N'รองรับรหัส Pantone ทั้งระบบ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.11', N'text', N'4–5');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.12', N'text', N'เกรดความคงทนสี ซัก/เหงื่อ/แสง');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.13', N'text', N'ส่งรหัสสีให้เราเทียบ →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.14', N'text', N'COLORWAY SPECIMEN');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.15', N'text', N'ΔE < 0.5 TOLERANCE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.16', N'text', N'L.Y. PRECISION WEAVE');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.17', N'text', N'SELECTED PANTONE®');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.18', N'text', N'AUTO DYE DISPENSER');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.19')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.19', N'text', N'ระบบจ่ายสีย้อมอัตโนมัติ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.20')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.20', N'text', N'SPECTROPHOTOMETER');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.21')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.21', N'text', N'วัดค่าสีด้วยเครื่อง ไม่ใช้สายตา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.22')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.22', N'text', N'LAB-DIP vs STANDARD');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'colorlab.23')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'colorlab.23', N'text', N'เทียบ Lab-dip กับมาตรฐานก่อนขึ้นไลน์');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'gallery.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'gallery.01', N'text', N'07 — INSPIRATION HUB');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'gallery.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'gallery.02', N'text', N'ตัวอย่างสินค้าของเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'gallery.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'gallery.03', N'text', N'ทุกชิ้นมีรหัสอ้างอิงเฉพาะ สั่งพัฒนาต่อยอด หรือขอตัวอย่างจริงเพื่อเทียบสัมผัสได้ทันที');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'gallery.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'gallery.04', N'text', N'ดูแคตตาล็อกทั้งหมด →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'faq.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'faq.01', N'text', N'08 — FAQ & SPECIFICATION');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'faq.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'faq.02', N'text', N'คำถามที่พบบ่อย');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'faq.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'faq.03', N'text', N'ข้อมูลเกี่ยวกับขั้นต่ำในการผลิต (MOQ), กระบวนการทำตัวอย่าง, มาตรฐานการเทียบสี และระยะเวลาจัดส่ง — ทีมฝ่ายขายพร้อมตอบทุกข้อสงสัยภายใน 24 ชั่วโมงทำการ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'faq.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'faq.04', N'text', N'สอบถามคำถามอื่นเพิ่มเติม →');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.01')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.01', N'text', N'GET IN TOUCH');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.02')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.02', N'text', N'เริ่มงาน Trims กับเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.03')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.03', N'text', N'ส่งตัวอย่าง แบบร่าง หรือสเปกที่คุณต้องการมาให้เรา — ทีมงานฝ่ายเทคนิคและฝ่าย Support พร้อมประเมินและตอบกลับภายใน 24 ชั่วโมงทำการ');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.04')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.04', N'text', N'ขอใบเสนอราคา / Request a Quote');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.05')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.05', N'text', N'L.Y. INDUSTRIES CO., LTD.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.06')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.06', N'text', N'OPERATING HOURS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.07')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.07', N'text', N'SITEMAP');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.08')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.08', N'text', N'หน้าแรก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.09')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.09', N'text', N'แคตาล็อกสินค้า');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.10')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.10', N'text', N'TRIMRITE®');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.11')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.11', N'text', N'เกี่ยวกับเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.12')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.12', N'text', N'ติดต่อเรา');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.13')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.13', N'text', N'คำถามพบบ่อย');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.14')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.14', N'text', N'QUALITY STANDARDS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.15')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.15', N'text', N'OEKO-TEX® Standard 100 Certified');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.16')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.16', N'text', N'สอดคล้องข้อกำหนด RSL ของแบรนด์กีฬาระดับโลก');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.17')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.17', N'text', N'© 2026 L.Y. INDUSTRIES CO., LTD. ALL RIGHTS RESERVED.');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.18')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.18', N'text', N'ALSO SERVING: UNDERWEAR · FOOTWEAR · BAGS');
IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = N'home' AND block_key = N'contact.19')
    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES (N'home', N'contact.19', N'text', N'BANGKOK, THAILAND · EST. 1978');

COMMIT TRANSACTION;

/* ตรวจผล */
SELECT page_slug, COUNT(*) AS blocks FROM dbo.lyiweb_blocks GROUP BY page_slug ORDER BY page_slug;
