<?php
declare(strict_types=1);

/**
 * Generates docs/sql/003_lyiweb_seed_site.sql from includes/site-defaults.php
 * (contact settings + page titles/descriptions). CLI only:  php tools/build-seed-site.php
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root     = dirname(__DIR__);
$defaults = require $root . '/includes/site-defaults.php';
$nstr     = static fn(string $s): string => "N'" . str_replace("'", "''", $s) . "'";

$sql = <<<'SQL'
/* =====================================================================
   003_lyiweb_seed_site.sql — ข้อมูลติดต่อ (lyiweb_settings) + ชื่อหน้า/คำอธิบาย SEO (lyiweb_pages)
   GENERATED by tools/build-seed-site.php from includes/site-defaults.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • รันซ้ำได้: settings ใส่เฉพาะ key ที่ยังไม่มี · pages เติมเฉพาะช่องที่ยังว่าง (NULL) — ไม่ทับค่าที่แก้ในหลังบ้านแล้ว
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* settings */

SQL;

foreach ($defaults['settings'] as $key => $value) {
    $sql .= "IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_settings WHERE setting_key = {$nstr($key)})\n"
          . "    INSERT dbo.lyiweb_settings (setting_key, value) VALUES ({$nstr($key)}, {$nstr($value)});\n";
}

$sql .= "\n/* pages (rows were created by 001_lyiweb_schema.sql) */\n";
foreach ($defaults['pages'] as $slug => $page) {
    foreach (['title_th', 'meta_desc_th'] as $col) {
        if ($page[$col] === '') {
            continue;
        }
        $sql .= "UPDATE dbo.lyiweb_pages SET {$col} = {$nstr($page[$col])}, updated_at = GETDATE() WHERE slug = {$nstr($slug)} AND {$col} IS NULL;\n";
    }
}

$sql .= <<<'SQL'

COMMIT TRANSACTION;

/* ตรวจผล */
SELECT setting_key, value FROM dbo.lyiweb_settings ORDER BY setting_key;
SELECT slug, title_th, LEN(meta_desc_th) AS meta_desc_len FROM dbo.lyiweb_pages ORDER BY id;

SQL;

$out = $root . '/docs/sql/003_lyiweb_seed_site.sql';
file_put_contents($out, $sql);
echo "wrote $out\n";
