<?php
declare(strict_types=1);

/**
 * Generates docs/sql/002_lyiweb_seed_home.sql from includes/home-data.php so the seed and the
 * built-in fallback can never drift. CLI only:  php tools/build-seed-home.php
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root   = dirname(__DIR__);
$schema = require $root . '/includes/schema/lists.php';
$data   = require $root . '/includes/home-data.php';

$nstr = static fn(?string $s): string => $s === null ? 'NULL' : "N'" . str_replace("'", "''", $s) . "'";
$json = static fn(array $a): ?string => $a === [] ? null : json_encode($a, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

$sql = <<<'SQL'
/* =====================================================================
   002_lyiweb_seed_home.sql — เนื้อหาปัจจุบันของหน้าแรก → lyiweb_items
   GENERATED by tools/build-seed-home.php from includes/home-data.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • รันซ้ำได้: แต่ละ list ใส่เฉพาะเมื่อยังไม่มีแถวของ list นั้นเลย (ไม่ทับเนื้อหาที่แก้ในหลังบ้านแล้ว)
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

SQL;

foreach ($schema as $key => $def) {
    $rows = $data[$key] ?? [];
    $sql .= "\n/* {$key} — {$def['title']} (" . count($rows) . " rows) */\n";
    $sql .= "IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_items WHERE list_key = {$nstr($key)})\nBEGIN\n";
    foreach ($rows as $i => $row) {
        $th = $common = [];
        foreach ($def['fields'] as $name => $f) {
            if ($f['i18n']) {
                $th[$name] = $row[$name];
            } else {
                $common[$name] = $row[$name];
            }
        }
        $sql .= sprintf(
            "    INSERT dbo.lyiweb_items (list_key, sort_order, data_th, data_en, data_common) VALUES (%s, %d, %s, NULL, %s);\n",
            $nstr($key), ($i + 1) * 10, $nstr($json($th)), $nstr($json($common))
        );
    }
    $sql .= "END\n";
}

$sql .= <<<'SQL'

COMMIT TRANSACTION;

/* ตรวจผล */
SELECT list_key, COUNT(*) AS rows_count FROM dbo.lyiweb_items GROUP BY list_key ORDER BY list_key;

SQL;

$out = $root . '/docs/sql/002_lyiweb_seed_home.sql';
file_put_contents($out, $sql);
echo "wrote $out\n";
