<?php
declare(strict_types=1);

/**
 * Generates docs/sql/004_lyiweb_seed_blocks.sql from every includes/blocks/<page>.php.
 * CLI only:  php tools/build-seed-blocks.php
 */

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$root = dirname(__DIR__);
$nstr = static fn(string $s): string => "N'" . str_replace("'", "''", $s) . "'";

$sql = <<<'SQL'
/* =====================================================================
   004_lyiweb_seed_blocks.sql — ข้อความของแต่ละหน้า → lyiweb_blocks
   GENERATED by tools/build-seed-blocks.php from includes/blocks/<page>.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • รันซ้ำได้: ใส่เฉพาะ block ที่ยังไม่มี (page_slug + block_key) — ไม่ทับข้อความที่แก้ในหลังบ้านแล้ว
   • เพิ่มหน้าใหม่ภายหลัง: generate ไฟล์นี้ใหม่แล้วรันซ้ำได้เลย
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

SQL;

$total = 0;
foreach (glob($root . '/includes/blocks/*.php') as $file) {
    $blocks = require $file;
    $sql .= "\n/* " . basename($file) . ' — ' . count($blocks) . " blocks */\n";
    foreach ($blocks as $fullKey => $text) {
        [$page, $key] = explode('.', $fullKey, 2);
        $sql .= "IF NOT EXISTS (SELECT 1 FROM dbo.lyiweb_blocks WHERE page_slug = {$nstr($page)} AND block_key = {$nstr($key)})\n"
              . "    INSERT dbo.lyiweb_blocks (page_slug, block_key, block_type, value_th) VALUES ({$nstr($page)}, {$nstr($key)}, N'text', {$nstr($text)});\n";
        $total++;
    }
}

$sql .= <<<'SQL'

COMMIT TRANSACTION;

/* ตรวจผล */
SELECT page_slug, COUNT(*) AS blocks FROM dbo.lyiweb_blocks GROUP BY page_slug ORDER BY page_slug;

SQL;

$out = $root . '/docs/sql/004_lyiweb_seed_blocks.sql';
file_put_contents($out, $sql);
echo "wrote $out ($total blocks)\n";
