<?php
declare(strict_types=1);

/**
 * Generates docs/sql/010_lyiweb_en_draft.sql from tools/data/en-draft.php (English draft texts).
 * The SQL only fills English fields that are still empty, so it is safe to re-run and never
 * overwrites a translation made in the admin. List items are matched by their exact Thai data as
 * read from the connected DB (test_LYI) — an item whose Thai was edited since is simply skipped.
 *
 * usage: php tools/build-en-draft.php
 */

$root = dirname(__DIR__);
require $root . '/includes/bootstrap.php';

$draft = require __DIR__ . '/data/en-draft.php';
$schema = require $root . '/includes/schema/lists.php';
$q = static fn(?string $s): string => $s === null ? 'NULL' : "N'" . str_replace("'", "''", $s) . "'";

// guard: every {placeholder} of the Thai default must survive in the English draft
$defaults = [];
foreach (glob($root . '/includes/blocks/*.php') as $f) {
    $defaults += require $f;
}
foreach ($draft['blocks'] as $key => $en) {
    if (!isset($defaults[$key])) {
        fwrite(STDERR, "unknown block $key\n");
        exit(1);
    }
    preg_match_all('/\{[a-z]+\}/', $defaults[$key], $need);
    foreach ($need[0] as $token) {
        if (!str_contains($en, $token)) {
            fwrite(STDERR, "$key: English draft lost $token\n");
            exit(1);
        }
    }
}

$sql = <<<'SQL'
/* =====================================================================
   010_lyiweb_en_draft.sql — ร่างคำแปลภาษาอังกฤษ (ให้ผู้รับผิดชอบเนื้อหา/Pack ตรวจแก้ในหลังบ้าน)
   GENERATED by tools/build-en-draft.php from tools/data/en-draft.php — ห้ามแก้มือ

   • รันใน test_LYI ก่อน แล้วค่อย LYI
   • ใส่เฉพาะช่องภาษาอังกฤษที่ยังว่าง — ไม่ทับคำแปลที่แก้ในหลังบ้านแล้ว · รันซ้ำได้
   • รายการ (FAQ, ขั้นตอนผลิต …) จับคู่ด้วยข้อความไทยเดิม — ถ้าแก้ภาษาไทยไปแล้วจะข้าม (แปลเองในหลังบ้าน)
   ===================================================================== */

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

/* page texts (lyiweb_blocks) */

SQL;
foreach ($draft['blocks'] as $key => $en) {
    [$page, $block] = explode('.', $key, 2);
    $sql .= 'UPDATE dbo.lyiweb_blocks SET value_en = ' . $q($en) . ', updated_at = GETDATE()'
          . ' WHERE page_slug = ' . $q($page) . ' AND block_key = ' . $q($block) . " AND (value_en IS NULL OR value_en = N'');\n";
}

$sql .= "\n/* page title + description (lyiweb_pages) */\n";
foreach ($draft['pages'] as $slug => [$title, $desc]) {
    $sql .= 'UPDATE dbo.lyiweb_pages SET'
          . " title_en = CASE WHEN ISNULL(title_en, N'') = N'' THEN " . $q($title) . ' ELSE title_en END,'
          . " meta_desc_en = CASE WHEN ISNULL(meta_desc_en, N'') = N'' THEN " . $q($desc) . ' ELSE meta_desc_en END'
          . ' WHERE slug = ' . $q($slug) . ";\n";
}

$sql .= "\n/* list items (lyiweb_items.data_en) — matched by their Thai data */\n";
$skipped = [];
foreach ($draft['items'] as $listKey => $byThai) {
    $i18n = array_keys(array_filter($schema[$listKey]['fields'], static fn($d) => $d['i18n']));
    $first = $i18n[0];
    $rows = db_rows('SELECT data_th FROM dbo.lyiweb_items WHERE list_key = ?', [$listKey]);
    foreach ($byThai as $thaiFirst => $en) {
        $match = null;
        foreach ($rows as $r) {
            if ((json_decode((string) $r['data_th'], true)[$first] ?? null) === $thaiFirst) {
                $match = (string) $r['data_th'];
                break;
            }
        }
        if ($match === null) {
            $skipped[] = "$listKey: $thaiFirst";
            continue;
        }
        $ordered = [];
        foreach ($i18n as $f) {
            if (isset($en[$f])) {
                $ordered[$f] = $en[$f];
            }
        }
        $sql .= 'UPDATE dbo.lyiweb_items SET data_en = ' . $q(json_encode($ordered, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) . ', updated_at = GETDATE()'
              . ' WHERE list_key = ' . $q($listKey) . ' AND data_th = ' . $q($match) . " AND (data_en IS NULL OR data_en = N'');\n";
    }
}

$sql .= "\nCOMMIT TRANSACTION;\n";
file_put_contents($root . '/docs/sql/010_lyiweb_en_draft.sql', $sql);
echo 'wrote docs/sql/010_lyiweb_en_draft.sql — ', count($draft['blocks']), ' texts, ', count($draft['pages']), ' pages, ',
     array_sum(array_map('count', $draft['items'])) - count($skipped), " list items\n";
foreach ($skipped as $s) {
    echo "  skipped (Thai changed in DB): $s\n";
}
